#!/usr/bin/python
# -*- coding: utf-8 -*-
#
# Copyright (©) 2012 Gustavo Noronha Silva
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as
#  published by the Free Software Foundation, either version 3 of the
#  License, or (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
#
#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.

import sys
if len(sys.argv) < 2:
    print 'Tell me which house!'
    sys.exit(1)

import os
appdir = os.path.dirname(__file__)
if not appdir:
    appdir = '.'
appdir = os.path.abspath(appdir)

if os.environ.has_key('PYTHONPATH'):
    os.environ['PYTHONPATH'] = '%s:' % (appdir) + os.environ['PYTHONPATH']
else:
    os.environ['PYTHONPATH'] = '%s:' % (appdir)

os.execve(sys.executable, [sys.executable, os.path.join(appdir, 'collector', 'collector.py'), '--source', sys.argv[1]], os.environ)

