# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-23 22:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(max_length=1000, verbose_name='Question')),
                ('answer', models.TextField(max_length=5000, verbose_name='Answer')),
                ('last_change', models.DateTimeField(auto_now=True, verbose_name='Last Change')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('site', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sites.Site', verbose_name='Site')),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQ',
            },
        ),
    ]
