# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-23 22:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import easy_thumbnails.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlternativeLegislatorName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2048)),
            ],
        ),
        migrations.CreateModel(
            name='ArchivedExpense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_id', models.CharField(blank=True, max_length=512, null=True, verbose_name='Original ID')),
                ('number', models.CharField(help_text='Usually a receipt ID.', max_length=512, verbose_name='Document number')),
                ('date', models.DateField(verbose_name='Expense date')),
                ('value', models.DecimalField(blank=True, decimal_places=2, help_text='The total amount spent.', max_digits=10, null=True, verbose_name='Value')),
                ('expensed', models.DecimalField(decimal_places=2, help_text='Amount reimbursed to the legislator.', max_digits=10, verbose_name='Expensed')),
            ],
            options={
                'verbose_name': 'Archived expense',
                'verbose_name_plural': 'Archived expenses',
            },
        ),
        migrations.CreateModel(
            name='BiggestSupplierForYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('expensed', models.DecimalField(decimal_places=2, max_digits=20)),
            ],
        ),
        migrations.CreateModel(
            name='CollectionRun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Collection date')),
                ('committed', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Collections',
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_id', models.CharField(blank=True, max_length=512, null=True, verbose_name='Original ID')),
                ('number', models.CharField(help_text='Usually a receipt ID.', max_length=512, verbose_name='Document number')),
                ('date', models.DateField(verbose_name='Expense date')),
                ('value', models.DecimalField(blank=True, decimal_places=2, help_text='The total amount spent.', max_digits=10, null=True, verbose_name='Value')),
                ('expensed', models.DecimalField(decimal_places=2, help_text='Amount reimbursed to the legislator.', max_digits=10, verbose_name='Expensed')),
            ],
            options={
                'verbose_name': 'Expense',
                'verbose_name_plural': 'Expenses',
            },
        ),
        migrations.CreateModel(
            name='ExpenseNature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_id', models.CharField(blank=True, max_length=512, null=True, verbose_name='Original ID')),
                ('name', models.CharField(max_length=512, verbose_name='Expense nature name')),
            ],
            options={
                'verbose_name': 'Expense nature',
                'verbose_name_plural': 'Expense natures',
            },
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2048, verbose_name='Name')),
                ('siglum', models.CharField(max_length=10, unique=True, verbose_name='Siglum')),
                ('logo', easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, upload_to=b'institution', verbose_name='Logo')),
            ],
            options={
                'verbose_name': 'Institution',
                'verbose_name_plural': 'Institutions',
            },
        ),
        migrations.CreateModel(
            name='Legislator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2048, verbose_name='Full name')),
                ('picture', easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, upload_to=b'legislator', verbose_name='Picture')),
                ('site', models.URLField(blank=True, null=True, verbose_name='Site')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('about', models.TextField(blank=True, null=True, verbose_name='About')),
                ('gender', models.CharField(blank=True, choices=[(b'F', 'Female'), (b'M', 'Male')], max_length=1, null=True, verbose_name='Gender')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Date of Birth')),
                ('alternative_names', models.ManyToManyField(to='montanha.AlternativeLegislatorName')),
            ],
            options={
                'verbose_name': 'Legislator',
                'verbose_name_plural': 'Legislators',
            },
        ),
        migrations.CreateModel(
            name='Legislature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_id', models.CharField(blank=True, max_length=512, null=True, verbose_name='Original ID')),
                ('date_start', models.DateField(help_text='Date in which this legislature started.', verbose_name='Date started')),
                ('date_end', models.DateField(blank=True, help_text='Date in which this legislature ended.', null=True, verbose_name='Date ended')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='montanha.Institution')),
            ],
            options={
                'verbose_name': 'Legislature',
                'verbose_name_plural': 'Legislatures',
            },
        ),
        migrations.CreateModel(
            name='Mandate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_id', models.TextField(blank=True, null=True)),
                ('date_start', models.DateField(help_text='Date in which this mandate started; may also be a resumption of a mandate that was paused for taking an executive-branch office, or a party change.', verbose_name='Date started')),
                ('date_end', models.DateField(blank=True, help_text='Date in which this mandate ended, paused for taking an executive-branch office, or affiliation change.', null=True, verbose_name='Date ended')),
                ('state', models.CharField(blank=True, help_text='The state where the legislator comes from.', max_length=512, null=True, verbose_name='State')),
                ('legislator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='montanha.Legislator')),
                ('legislature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='montanha.Legislature')),
            ],
            options={
                'verbose_name': 'Mandate',
                'verbose_name_plural': 'Mandates',
            },
        ),
        migrations.CreateModel(
            name='PerLegislator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateField()),
                ('date_end', models.DateField()),
                ('expensed', models.DecimalField(decimal_places=2, max_digits=20)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='montanha.Institution')),
                ('legislator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='montanha.Legislator')),
                ('legislature', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='montanha.Legislature')),
            ],
        ),
        migrations.CreateModel(
            name='PerNature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateField()),
                ('date_end', models.DateField()),
                ('expensed', models.DecimalField(decimal_places=2, max_digits=20)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='montanha.Institution')),
                ('legislature', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='montanha.Legislature')),
                ('nature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='montanha.ExpenseNature')),
            ],
        ),
        migrations.CreateModel(
            name='PerNatureByMonth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('expensed', models.DecimalField(decimal_places=2, max_digits=20)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='montanha.Institution')),
                ('nature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='montanha.ExpenseNature')),
            ],
        ),
        migrations.CreateModel(
            name='PerNatureByYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('expensed', models.DecimalField(decimal_places=2, max_digits=20)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='montanha.Institution')),
                ('nature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='montanha.ExpenseNature')),
            ],
        ),
        migrations.CreateModel(
            name='PoliticalParty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('siglum', models.CharField(max_length=15, unique=True, verbose_name='Siglum')),
                ('name', models.CharField(blank=True, max_length=2048, null=True, verbose_name='Full name')),
                ('logo', easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, upload_to=b'political_party', verbose_name='Logo')),
                ('wikipedia', models.URLField(blank=True, null=True, verbose_name='Wikipedia')),
            ],
            options={
                'verbose_name': 'Political Party',
                'verbose_name_plural': 'Political Parties',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('identifier', models.CharField(max_length=256, verbose_name='Supplier identifier')),
                ('date_opened', models.DateField(blank=True, null=True, verbose_name='Date Opened')),
                ('trade_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Trade Name')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Address')),
                ('juridical_nature', models.CharField(blank=True, max_length=200, null=True, verbose_name='Juridical Nature')),
                ('status', models.NullBooleanField(verbose_name='Status')),
                ('main_economic_activity', models.CharField(blank=True, max_length=200, null=True, verbose_name='Main Economic Activity')),
                ('last_change', models.DateTimeField(auto_now=True, null=True, verbose_name='Last Change')),
            ],
            options={
                'verbose_name': 'Supplier',
                'verbose_name_plural': 'Suppliers',
            },
        ),
        migrations.AddField(
            model_name='mandate',
            name='party',
            field=models.ForeignKey(blank=True, help_text='Party the legislator was affiliated to during this mandate.', null=True, on_delete=django.db.models.deletion.CASCADE, to='montanha.PoliticalParty', verbose_name='Party'),
        ),
        migrations.AddField(
            model_name='expense',
            name='mandate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='montanha.Mandate'),
        ),
        migrations.AddField(
            model_name='expense',
            name='nature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='montanha.ExpenseNature'),
        ),
        migrations.AddField(
            model_name='expense',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='montanha.Supplier'),
        ),
        migrations.AddField(
            model_name='collectionrun',
            name='legislature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='montanha.Legislature'),
        ),
        migrations.AddField(
            model_name='biggestsupplierforyear',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='montanha.Supplier'),
        ),
        migrations.AddField(
            model_name='archivedexpense',
            name='collection_run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='montanha.CollectionRun'),
        ),
        migrations.AddField(
            model_name='archivedexpense',
            name='mandate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='montanha.Mandate'),
        ),
        migrations.AddField(
            model_name='archivedexpense',
            name='nature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='montanha.ExpenseNature'),
        ),
        migrations.AddField(
            model_name='archivedexpense',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='montanha.Supplier'),
        ),
    ]
