# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-28 19:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('montanha', '0004_auto_20171025_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivedexpense',
            name='date',
            field=models.DateField(db_index=True, verbose_name='Expense date'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(db_index=True, verbose_name='Expense date'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='identifier',
            field=models.CharField(db_index=True, max_length=256, verbose_name='Supplier identifier'),
        ),
    ]
