# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-14 20:21
from __future__ import unicode_literals

from django.db import migrations
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('montanha', '0005_auto_20171028_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legislator',
            name='picture',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, max_length=256, null=True, upload_to=b'legislator', verbose_name='Picture'),
        ),
    ]
